
on: push

name: Test ipify.js

jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - run: npm install
      - run: npm test

